[add_iq_imbalance]

is_class = false
frontend_name = "Add frequency IQ imbalance"
description = "Add frequency IQ imbalance to signal"
is_analyzer = false

[add_iq_imbalance.input]
signals = "Input signals"

[add_iq_imbalance.output]
signals = "Output signals"
