[bits_error_count]

is_class = false
frontend_name = "Bits error counter"
description = "Count bits error for signal"
is_analyzer = true

[bits_error_count.parameters]

[bits_error_count.parameters.bits_per_symbol]
frontend_name = "bits per symbol"
data_type = "int"
value = "6"
unit = ""
unit_type = ""

[bits_error_count.input]
signals = "Input signals"

prev_symbols = "Previous input symbolss"

[bits_error_count.output]
ber = "Bits error rate"
q_factor = "Q factor (db)"
