[fiber]

is_class = false
frontend_name = "Optical fiber"
description = "Single core single mode dual polarization fiber"
is_analyzer = false

[fiber.parameters]

[fiber.parameters.sampling_rate]
frontend_name = "Sampling rate"
data_type = "float"
value = "1024000000000"
unit = "hz"
unit_type = "frequency"

[fiber.parameters.num_spans]
frontend_name = "Number of spans"
data_type = "int"
value = "5"
unit = ""
unit_type = ""

[fiber.parameters.beta2]
frontend_name = "beta2"
data_type = "float"
value = "0.0000000000000000000000216676"
unit = ""
unit_type = ""

[fiber.parameters.delta_z]
frontend_name = "Step length"
data_type = "float"
value = "1"
unit = ""
unit_type = ""

[fiber.parameters.gamma]
frontend_name = "gamma"
data_type = "float"
value = "1.3"
unit = ""
unit_type = ""

[fiber.parameters.alpha]
frontend_name = "alpha"
data_type = "float"
value = "0.2"
unit = ""
unit_type = ""

[fiber.parameters.span_length]
frontend_name = "Span length"
data_type = "int"
value = "75"
unit = "km"
unit_type = "length"

[fiber.input]
signals = "Tx (transmit) signals"

[fiber.output]
signals = "Output signals"

signals_power = "Output signals power"
