# 底层运算库的代码
# signal_x, signal_y = phot.gaussian_noise(signal_x, signal_y, osnr_db, sampling_rate)

[gaussian_noise] # 函数在底层运算库的名字

is_class = false                  # 意思是：这不是类，这是函数
frontend_name = "Gaussian noise"  # 前端的名字
description = "根据设置的OSNR来加入高斯白噪声" # 描述信息
is_analyzer = false               # 是否为分析器

[gaussian_noise.parameters] # 函数参数

[gaussian_noise.parameters.osnr_db]
frontend_name = "OSNR" # 前端显示名称
data_type = "float"    # 该参数的数据类型，方便进行数据类型转换
value = "50"           # 该参数的默认值
unit = "db"            # 分贝
unit_type = "sound"    # The intensity of a sound

[gaussian_noise.parameters.sampling_rate]
frontend_name = "Sampling rate" # 前端显示名称
data_type = "int"               # 该参数的数据类型，方便进行数据类型转换
value = "40000000000"           # 该参数的默认值
unit = "hz"                     # 底层运算库的默认单位，比如“m”，“km”
unit_type = "frequency"         # 底层运算库的单位类型，比如“length”、“frequency”

[gaussian_noise.input]

# Key：底层运算库的名字，Value：前端显示的名字
signal_x = "Input signal x"
signal_y = "Input signal y"

[gaussian_noise.output]

signal_x = "Output signal x"
signal_y = "Output signal y"
