[iq_compensation]
is_class = false
frontend_name = "IQ compensation"
description = "IQ正交化补偿"
is_analyzer = false

[iq_compensation.parameters]

[iq_compensation.parameters.sampling_rate]
frontend_name = "Sampling rate"
data_type = "float"
value = "1024000000000"
unit = "hz"
unit_type = "frequency"

[iq_compensation.parameters.beta2]
frontend_name = "beta2"
data_type = "float"
value = "0.0000000000000000000000216676"
unit = ""
unit_type = ""

[iq_compensation.parameters.span]
frontend_name = "Simulation span"
data_type = "int"
value = "5"
unit = ""
unit_type = ""

[iq_compensation.parameters.L]
frontend_name = "Length"
data_type = "int"
value = "75"
unit = "km"
unit_type = "length"

[iq_compensation.input]

signals = "Input signals"
signals_power = "Input signals power"

[iq_compensation.output]
signals = "Output signals"
