[sync_frame]

is_class = false
frontend_name = "Synchronize frame"
description = "Synchronize frame for signal"
is_analyzer = false

[sync_frame.parameters]

[sync_frame.parameters.up_sampling_factor]
frontend_name = "up sampling factor"
data_type = "int"
value = "2"
unit = ""
unit_type = ""

[sync_frame.input]
signals = "Input signals"

prev_symbols = "Input previous symbols"

[sync_frame.output]
signals = "Output signals"

prev_symbols = "Output previous symbols"
