[transmitter]

is_class = false
frontend_name = "Transmitter"
description = "发射机"
is_analyzer = false

[transmitter.parameters]

[transmitter.parameters.num_symbols]
frontend_name = "Number of symbols"
data_type = "int"
value = "65536"
unit = ""
unit_type = ""

[transmitter.parameters.bits_per_symbol]
frontend_name = "bits per symbol"
data_type = "int"
value = "4"
unit = ""
unit_type = ""

[transmitter.parameters.total_baud]
frontend_name = "total baud rate"
data_type = "int"
value = "10000000000"
unit = ""
unit_type = ""

[transmitter.parameters.up_sampling_factor]
frontend_name = "up sampling factor"
data_type = "int"
value = "2"
unit = ""
unit_type = ""

[transmitter.parameters.RRC_ROLL_OFF]
frontend_name = "RRC pulse shaping roll-off factor"
data_type = "float"
value = "0.02"
unit = ""
unit_type = ""

[transmitter.parameters.sampling_rate_awg]
frontend_name = "Sampling rate AWG"
data_type = "int"
value = "96000000000"
unit = "hz"
unit_type = "frequency"

[transmitter.parameters.dac_resolution_bits]
frontend_name = "DAC resolution bits"
data_type = "int"
value = "8"
unit = ""
unit_type = ""

[transmitter.parameters.linewidth_tx]
frontend_name = "Transmitter laser linewidth"
data_type = "int"
value = "150000"
unit = ""
unit_type = ""

[transmitter.parameters.osnr_db]
frontend_name = "System OSNR"
data_type = "int"
value = "30"
unit = ""
unit_type = ""

[transmitter.output]
signals = "Output signals"
prev_symbols = "Previous symbols"
